function [APP] = create_figure()
%%
% 
%  main function which handles figure creation
%  
%  INPUT: [none]
%  
%  OUTPUT: APP, struct which contains all graphical components and
%          information for the current instance of the application
%  

%% determine measurements for each component
%  
[SCR,PAN,TRAJ,SIG,OBJ,USEL] = dimensions_normalized();

%% main figure, axes, and sliders
APP.MAIN = figure('units','normalized',...
				  'position',SCR(1,:),...
				  'menubar','none',...
				  'name','dNEMO',...
				  'numbertitle','off',...
				  'resize','on');

APP.ax1 = axes('units','normalized',...
			   'position',SCR(2,:),...
			   'YDir','reverse',...
			   'XTick',[],...
			   'YTick',[]);
%
APP.ax2 = axes('units','normalized',...
			   'position',SCR(2,:),...
			   'color','none',...
			   'YDir','reverse',...
			   'XAxisLocation','top',...
			   'XLimMode','manual',...
			   'YLimMode','manual',...
			   'hittest','on',...
			   'pickableparts','visible',...
			   'NextPlot','add',...
			   'XTick',[],...
			   'YTick',[]);
%
APP.film_slider = uicontrol('style','slide',...
							'unit','normalized',...
							'position',SCR(3,:),...
							'min',1,...
							'max',1,...
							'val',1,...
							'visible','on',...
							'enable','off');
%
APP.z_slice_slider = uicontrol('style','slide',...
							   'units','normalized',...
							   'position',SCR(4,:),...
							   'min',1,...
							   'max',1,...
							   'val',1,...
							   'visible','off',...
							   'enable','off');
%
APP.curr_frame_display = annotation(APP.MAIN,'textbox',SCR(2,:),...
                                    'String','T = TEST',...
                                    'color','red',...
                                    'HorizontalAlignment','right',...
                                    'VerticalAlignment','bottom',...
                                    'EdgeColor','none',...
                                    'FontSize',14,...
                                    'FitBoxToText','on',...
                                    'visible','off');
                               
%% spot filter panel
APP.signal_filter_panel = uipanel('units','normalized',...
								  'position',PAN(1,:),...
								  'Title','Spot Filter');
%
APP.hist_ax = axes('parent',APP.signal_filter_panel,...
                   'units','normalized',...
				   'position',[0.1 0.25 0.475 0.475],...
				   'XTick',[],...
				   'YTick',[],...
				   'HitTest','on',...
				   'PickableParts','Visible',...
				   'NextPlot','add',...
                   'visible','on');
%
APP.current_threshold_label = uicontrol('style','text',...
                                      'parent',APP.signal_filter_panel,...
                                      'units','normalized',...
                                      'position',SIG(2,:),...
                                      'string',{'Wavelet';'Threshold'},...
                                      'HorizontalAlignment','left',...
                                      'enable','on',...
                                      'visible','on');
%
APP.current_threshold_display = uicontrol('style','edit',...
                                        'parent',APP.signal_filter_panel,...
                                        'units','normalized',...
                                        'position',SIG(3,:),...
                                        'string','2',...
                                        'enable','off',...
                                        'visible','on');
%
APP.current_threshold_slider = uicontrol('style','slide',...
                                       'parent',APP.signal_filter_panel,...
                                       'units','normalized',...
                                       'position',SIG(4,:),...
                                       'min',0,...
                                       'max',10,...
                                       'value',2,...
                                       'SliderStep',[0.01 0.12],...
                                       'enable','off');
%{
APP.start_frame_label = uicontrol('style','text',...
                                'parent',APP.signal_filter_panel,...
                                'units','normalized',...
                                'position',SIG(5,:),...
                                'string',{'Beginning';'at frame'},...
                                'enable','off',...
                                'visible','on');
%
APP.start_frame_input = uicontrol('style','edit',...
                                'parent',APP.signal_filter_panel,...
								'units','normalized',...
								'position',SIG(6,:),...
								'string','1',...
								'enable','off',...
								'visible','on');
%
APP.end_frame_label = uicontrol('style','text',...
                              'parent',APP.signal_filter_panel,...
							  'units','normalized',...
							  'position',SIG(7,:),...
								'string','Ending at frame:',...
								'enable','off',...
								'visible','on');
%
APP.end_frame_input = uicontrol('style','edit',...
                              'parent',APP.signal_filter_panel,...
							  'units','normalized',...
							  'position',SIG(8,:),...
							  'string','1',...
							  'enable','off',...
							  'visible','on');
%}
APP.quick_detect_button = uicontrol('style','push',...
                                    'parent',APP.signal_filter_panel,...
                                    'units','normalized',...
                                    'position',[0.6 0.8 0.18 0.18],...
                                    'string','Test Detect (Fast)',...
                                    'enable','off',...
                                    'visible','on');
%
APP.full_detect_button = uicontrol('style','push',...
                                   'parent',APP.signal_filter_panel,...
                                   'units','normalized',...
                                   'position',[0.8 0.8 0.18 0.18],...
                                   'string','Test Detect (Full)',...
                                   'enable','off',...
                                   'visible','on');
%
APP.create_keyframe_button = uicontrol('style','push',...
                                       'parent',APP.signal_filter_panel,...
                                       'units','normalized',...
                                       'position',[0.7 0.05 0.275 0.3],...
                                       'string','CREATE KEYFRAME',...
                                       'enable','off',...
                                       'visible','on');
%{
APP.hist_ax_intensity_measure = uicontrol('style','edit',...
                                          'parent',APP.signal_filter_panel,...
                                          'units','normalized',...
                                          'position',SIG(10,:),...
                                          'string','',...
                                          'visible','on');
%}
APP.hist_ax_min_label = uicontrol('style','text',...
                                  'parent',APP.signal_filter_panel,...
                                  'units','normalized',...
                                  'position',[0.6, 0.55 0.05 0.075],...
                                  'String','MIN');
%
APP.hist_ax_min_box = uicontrol('style','edit',...
                                'parent',APP.signal_filter_panel,...
                                'units','normalized',...
                                'position',[0.665 0.55 0.115 0.125],...
                                'string','',...
                                'visible','on',...
                                'tag','HISTMIN');
%
APP.hist_ax_max_label = uicontrol('style','text',...
                                  'parent',APP.signal_filter_panel,...
                                  'units','normalized',...
                                  'position',[0.6 0.4 0.05 0.075],...
                                  'string','MAX',...
                                  'visible','on');
%}
APP.hist_ax_max_box = uicontrol('style','edit',...
                                'parent',APP.signal_filter_panel,...
                                'units','normalized',...
                                'position',[0.665 0.4 0.115 0.125],...
                                'string','',...
                                'visible','on',...
                                'tag','HISTMAX');
%{
APP.hist_ax_bg = uibuttongroup(APP.MAIN,...
                               'units','normalized',...
                               'Position',SIG(15,:),...
                               'parent',APP.signal_filter_panel,...
                               'title','',...
                               'bordertype','none',...
                               'visible','on');
%
APP.hist_ax_bg_01 = uicontrol(APP.hist_ax_bg,...
                                     'style','radiobutton',...
                                     'units','normalized',...
                                     'Position',SIG(16,:),...
                                     'String','Intensity',...
                                     'Tag','INT',...
                                     'value',0,...
                                     'visible','on',...
                                     'enable','off');
%
APP.hist_ax_bg_02 = uicontrol(APP.hist_ax_bg,'style','radiobutton',...
                                                  'units','normalized',...
                                                  'Position',SIG(17,:),...
                                                  'String','Size',...
                                                  'Tag','SIZE',...
                                                  'value',0,...
                                                  'visible','on',...
                                                  'enable','off');
%}
APP.feature_select_dropdown = uicontrol('style','popupmenu',...
                                        'parent',APP.signal_filter_panel,...
                                        'units','normalized',...
                                        'position',[0.24 0.01 0.2 0.125],...
                                        'value',1,...
                                        'string',{''},...
                                        'enable','off',...
                                        'visible','on');
%
%% object creation / deletion panel
APP.cell_creation_panel = uipanel('units','normalized',...
								  'position',[0.61 0.55 0.095 0.1995],...
								  'title','Cells');
%
APP.keyframes_panel = uipanel('units','normalized',...
                              'position',[0.71 0.55 0.28 0.1995],...
                              'title','Keyframes');
%
APP.add_object_button = uicontrol('style','push',...
                                  'parent',APP.cell_creation_panel,...
								  'units','normalized',...
                                  'position',[0.05 0.7 0.9 0.26],...
								  'enable','off',...
								  'visible','on',...
								  'string','Add Cell',...
								  'value',0);
%
APP.modify_cell_button = uicontrol('style','push',...
                                   'parent',APP.cell_creation_panel,...
                                   'units','normalized',...
                                   'position',[0.05 0.42 0.9 0.26],...
								   'enable','off',...
								   'string','Modify Cell',...
								   'visible','on',...
                                   'tag','0');
%
%
APP.cell_label = uicontrol('style','text',...
                           'parent',APP.cell_creation_panel,...
                           'units','normalized',...
                           'position',[0.05 0.225 0.9 0.15],...
                           'string','Cell Selection',...
                           'HorizontalAlignment','left',...
                           'enable','on',...
                           'visible','on');
%
S = cell(1);
S{1} = 'N/A';
APP.created_cell_selection = uicontrol('style','pop',...
                                       'parent',APP.cell_creation_panel,...
                                       'units','normalized',...
                                       'position',[0.05 0.05 0.9 0.195],...
                                       'string',S,...
                                       'val',1,...
                                       'visible','on',...
                                       'enable','inactive');
%
%{
APP.add_spots_button = uicontrol('style','push',...
                                 'parent',APP.cell_creation_panel,...
                                 'units','normalized',...
                                 'position',OBJ(1,:),...
                                 'enable','off',...
                                 'visible','on',...
                                 'string','Start',...
                                 'value',0);
%}
APP.keyframing_map = uicontrol('style','listbox',...
                             'parent',APP.keyframes_panel,...
                             'units','normalized',...
                             'position',[0.075 0.1 0.85 0.735],...
                             'enable','on',...
                             'visible','on');
%
APP.keyframe_details = uicontrol('style','listbox',...
                                 'parent',APP.keyframes_panel,...
                                 'units','normalized',...
                                 'position',[0.075 0.1 0.85 0.735],...
                                 'enable','off',...
                                 'visible','off');
%{
APP.modify_cell_button = uicontrol('style','push',...
                                   'parent',APP.cell_creation_panel,...
                                   'units','normalized',...
                                   'position',OBJ(2,:),...
								   'enable','off',...
								   'string','Modify Cell',...
								   'visible','on',...
                                   'tag','0');
%
APP.delete_object_button = uicontrol('style','push',...
                                     'parent',APP.cell_creation_panel,...
								     'units','normalized',...
                                     'position',OBJ(3,:),...
								     'enable','off',...
								     'visible','on',...
								     'string','Delete Cell',...
								     'value',0);
%
APP.add_keyframe_button = uicontrol('style','push',...
                                  'parent',APP.cell_creation_panel,...
                                  'units','normalized',...
                                  'position',OBJ(4,:),...
								  'enable','off',...
								  'visible','on',...
								  'string','Add Keyframe');
%
APP.modify_keyframe_button = uicontrol('style','push',...
                                       'parent',APP.cell_creation_panel,...
                                       'units','normalized',...
                                       'position',OBJ(5,:),...
									   'enable','off',...
									   'string','Modify Keyframe',...
									   'visible','on');
%
APP.del_keyframe_button = uicontrol('style','push',...
                                    'parent',APP.cell_creation_panel,...
                                    'units','normalized',...
                                    'position',OBJ(6,:),...
								    'enable','off',...
								    'visible','on',...
								    'string','Delete Keyframe');
%
APP.curr_keyframe_details_pan = uipanel('parent',APP.cell_creation_panel,...
                                        'units','normalized',...
                                        'position',OBJ(10,:),...
                                        'title','',...
                                        'bordertype','line',...
                                        'highlightcolor',[0.5 0.5 0.5],...
                                        'tag','curr');
%
APP.curr_keyframe_details = uicontrol('style','text',...
                                      'parent',APP.cell_creation_panel,...
                                      'units','normalized',...
                                      'position',OBJ(8,:),...
                                      'string','Current Keyframe Details',...
                                      'enable','on',...
                                      'visible','on',...
                                      'horizontalalignment','left',...
                                      'tag','curr');
%
APP.all_keyframe_details_pan = uipanel('parent',APP.cell_creation_panel,...
                                       'units','normalized',...
                                       'position',OBJ(11,:),...
                                       'title','',...
                                       'bordertype','line',...
                                       'highlightcolor',[0.5 0.5 0.5],...
                                       'tag','all');
%
APP.all_keyframe_details = uicontrol('style','text',...
                                     'parent',APP.cell_creation_panel,...
                                     'units','normalized',...
                                     'position',OBJ(9,:),...
                                     'string','View All Keyframes',...
                                     'enable','off',...
                                     'visible','on',...
                                     'horizontalalignment','right',...
                                     'tag','all');
%
APP.keyframe_information_box = uicontrol('style','edit',...
                                       'parent',APP.cell_creation_panel,...
                                       'units','normalized',...
                                       'position',OBJ(7,:),...
                                       'enable','inactive',...
                                       'visible','on',...
                                       'string','',...
									   'min',0,'max',4,...
									   'horizontalalignment','left',...
									   'fontsize',13);
%
APP.keyframe_map = axes('parent',APP.cell_creation_panel,...
                        'units','normalized',...
                        'position',OBJ(7,:),...
                        'box','on',...% 'XTick',[],...% 'YTick',[],...
                        'visible','off',...
                        'NextPlot','add');
%
S = cell(1);
S{1} = 'N/A';
APP.keyframe_selection = uicontrol('style','pop',...
                                   'parent',APP.cell_creation_panel,...
                                   'units','normalized',...
                                   'position',OBJ(12,:),...
                                   'String',S,...
                                   'Value',1,...
                                   'visible','on');
%}
%% display manipulation panel
APP.removal_panel = uipanel('units','normalized',...
                            'position',[0.61 0.4005 0.095 0.1495],...
                            'title','Manual Removal');
%
APP.user_selection_panel = uipanel('units','normalized',...
								   'position',[0.71 0.4005 0.28 0.1495],...
								   'title','Display');
% [0.02 0.745 0.2 0.195]
APP.b_label = uicontrol('style','text',...
                        'parent',APP.user_selection_panel,...
                        'units','normalized',...
                        'position',[0.02 0.745 0.2 0.195],...
					    'string','Brightness',...
                        'HorizontalAlignment','left');
% [0.02 0.7 0.21 0.075]
APP.brightness_slider = uicontrol('style','slider',...
                                  'parent',APP.user_selection_panel,...
								  'units','normalized',...
								  'position',[0.02 0.65 0.36 0.125],...
								  'min',-100,'max',100,...
								  'SliderStep',[0.01 0.01],...
								  'value',0,...
								  'enable','off');
% [0.02 0.295 0.2 0.195]
APP.c_label = uicontrol('style','text',...
                        'parent',APP.user_selection_panel,...
				        'units','normalized',...
                        'position',[0.02 0.295 0.2 0.195],...
					    'string','Contrast',...
                        'HorizontalAlignment','left');
% [0.02 0.25 0.21 0.075]
APP.contrast_slider = uicontrol('style','slider',...
                                'parent',APP.user_selection_panel,...
							    'units','normalized',...
							    'position',[0.02 0.2 0.36 0.125],...
							    'min',45,'max',75,...
							    'value',49,...
							    'SliderStep',[0.01 0.01],...
							    'enable','off');
% original contrast slider vals -- 1, 74
% [0.28 0.8 0.4 0.18]
APP.frame_signal_toggle = uicontrol('style','checkbox',...
                                    'parent',APP.user_selection_panel,...
                                    'units','normalized',...
                                    'position',[0.4 0.8 0.58 0.18],...
								    'string','Display All Signals in Current Frame',...
								    'enable','off');
% [0.28 0.55 0.4 0.18]
APP.cell_signal_toggle = uicontrol('style','checkbox',...
                                   'parent',APP.user_selection_panel,...
								   'units','normalized',...
								   'position',[0.4 0.55 0.58 0.18],...
								   'string','Display All Signals in Cells',...
								   'value',0,...
								   'enable','off');
% [0.28 0.30 0.4 0.18]
APP.cell_boundary_toggle = uicontrol('style','checkbox',...
                                     'parent',APP.user_selection_panel,...
								     'units','normalized',...
								     'position',[0.4 0.3 0.58 0.18],...
								     'string','Display Cell Boundaries',...
								     'enable','off',...
								     'value',0);
% [0.28 0.05 0.4 0.18]
APP.excluded_signal_toggle = uicontrol('style','checkbox',...
                                       'parent',APP.user_selection_panel,...
									   'units','normalized',...
									   'position',[0.4 0.05 0.58 0.18],...
									   'string','Display Excluded Signals',...
									   'value',0,...
									   'enable','off',...
									   'visible','on');
%{
APP.cell_label = uicontrol('style','text',...
                           'parent',APP.user_selection_panel,...
                           'units','normalized',...
                           'position',USEL(9,:),...
                           'string','Cells',...
                           'HorizontalAlignment','left',...
                           'enable','on',...
                           'visible','on');
%
S = cell(1);
S{1} = 'N/A';
APP.created_cell_selection = uicontrol('style','pop',...
                                       'parent',APP.user_selection_panel,...
                                       'units','normalized',...
                                       'position',USEL(10,:),...
                                       'string',S,...
                                       'val',1,...
                                       'visible','on',...
                                       'enable','inactive');
%}
APP.remove_signals_button = uicontrol('style','push',...
                                      'parent',APP.removal_panel,...
                                      'units','normalized',...
                                      'position',[0.05 0.55 0.9 0.35],...
                                      'enable','off',...
                                      'visible','on',...
                                      'String','Remove Signals',...
                                      'value',0);
%
APP.removal_kf_button = uicontrol('style','push',...
                                  'parent',APP.removal_panel,...
                                  'units','normalized',...
                                  'position',[0.05 0.05 0.9 0.35],...
                                  'enable','off',...
                                  'visible','on',...
                                  'String','Update Removal Keyframe',...
                                  'value',0);
%
%% trajectory axis
APP.trajectory_ax = axes('units','normalized',...
						 'Position',TRAJ(1,:),...
						 'tag','trajectory',...
						 'visible','on',...
						 'pickableparts','none',...
						 'hittest','off',...
						 'NextPlot','add');
%
APP.signal_visualization_box = axes('units','normalized',...
									'Position',TRAJ(1,:),...
									'tag','visualization',...
									'YDir','reverse',...
									'XAxisLocation','top',...
									'visible','off',...
									'pickableparts','visible',...
									'hittest','off');
%
APP.sig_traj_bg = uibuttongroup(APP.MAIN,...
                                'units','normalized',...
                                'Position',TRAJ(2,:),...
                                'title','',...
                                'bordertype','none',...
                                'visible','off');
%
APP.sig_traj_rb1 = uicontrol(APP.sig_traj_bg,...
                             'style','radiobutton',...
                             'units','normalized',...
                             'Position',TRAJ(3,:),...
                             'tag','#1',...
                             'value',1,...
                             'visible','on',...
                             'enable','on');
%
APP.sig_traj_rb2 = uicontrol(APP.sig_traj_bg,...
                             'style','radiobutton',...
                             'units','normalized',...
                             'Position',TRAJ(4,:),...
                             'tag','#2',...
                             'value',0,...
                             'visible','on',...
                             'enable','on');
%


%% toolbar essentials
%  zoom in / zoom out / pan / 
set(APP.MAIN,'toolbar','figure');
tmp_cell_array = {'Show Plot Tools and Dock Figure','Hide Plot Tools',...
                    'Print Figure','Save Figure','Open File',...
                    'New Figure','Insert Legend','Insert Colorbar',...
                    'Data Cursor','Rotate 3D','Link Plot','Edit Plot',...
                    'Brush/Select Data'};
tooltip_string_array = string(tmp_cell_array);
a = findall(gcf);
for i=1:size(tooltip_string_array,2)
    tmp_string = char(tooltip_string_array(1,i));
    b = findall(a,'ToolTipString',tmp_string);
    set(b,'Visible','off');
end

%% menu assignments
%
% FILE
file_menu = uimenu(APP.MAIN,'label','File');
file_menu_open = uimenu(file_menu,'label','Load Images');
file_menu_save = uimenu(file_menu,'label','Save');
file_menu_reload = uimenu(file_menu,'label','Reload Results');
file_menu_directory = uimenu(file_menu,'label','Change Directory');
file_menu_image_src = uimenu(file_menu_directory,'label','Images');
file_menu_image_results = uimenu(file_menu_directory,'label','Results');
file_menu_mod = uimenu(file_menu,'label','Run Add Mods');
%

% IMAGE HANDLING
image_menu = uimenu(APP.MAIN,'label','Image');
% image_menu_data = uimenu(image_menu,'label','Current Source Image');
image_menu_display = uimenu(image_menu,'label','3D Display');
display_menu_01 = uimenu(image_menu_display,'label','Max Z-Project','checked','on');
display_menu_03 = uimenu(image_menu_display,'label','Full 3D Stack');
image_menu_channel = uimenu(image_menu,'label','Set Image Channel');
image_menu_import = uimenu(image_menu,'label','Import Reference Image');
image_menu_mask = uimenu(image_menu, 'label', 'Import Cell Mask TIFF');
image_menu_csv = uimenu(image_menu, 'label', 'Import Cell Mask CSV/XLS');

% SPOT DETECTION SETTINGS
settings_menu = uimenu(APP.MAIN,'label','Settings');
settings_menu_search = uimenu(settings_menu,'label','Signal Parameters');
% settings_menu_detect = uimenu(settings_menu,'label','Detection Method');
% settings_menu_default = uimenu(settings_menu,'label','Apply Default');
%

% display_menu = uimenu(APP.MAIN,'label','3D Display');
% display_menu_01 = uimenu(display_menu,'label','Max Z-Project','checked','on');
% display_menu_02 = uimenu(display_menu,'label','Icy MIP');
% display_menu_03 = uimenu(display_menu,'label','Full 3D Stack');

parallel_menu = uimenu(APP.MAIN,'label','Parallel Computing');
parallel_menu_01 = uimenu(parallel_menu,'label','Toggle Parallel Pool');
parallel_menu_02 = uimenu(parallel_menu,'label','Pool Preferences');

%% color matrix global variable
co = [0 0.4470 0.7410; 0.8500 0.3250 0.0980; 0.9290 0.6940 0.1250; 0.4940 0.1840 0.5560; 0.4660 0.6740 0.1880; 0.3010 0.7450 0.9330; 0.6350 0.0780 0.1840];
setappdata(APP.MAIN,'color_matrix',co);
% setappdata(APP.MAIN,'co',co);

%% initial settings assignment (wav transform)
APP_PARAM = struct;
APP_PARAM.WAV_LEVEL = 2;
APP_PARAM.FRAME_LIMIT = 2;
APP_PARAM.OVERSEG = 1;
APP_PARAM.NUM_PIX_OFF = 1;
APP_PARAM.NUM_PIX_BG = 1;
APP_PARAM.INT_MEASURE = 'MEAN';
APP_PARAM.SIG_MEASURE = 'ZCOORD';

setappdata(APP.MAIN,'APP_PARAM',APP_PARAM);
setappdata(APP.MAIN,'GLOBAL_APP_PARAM',APP_PARAM);

%% callback assignments
set(file_menu_open,'callback',{@file_load,APP});
set(file_menu_save,'callback',{@file_save,APP});
set(file_menu_reload,'callback',{@file_reload,APP});
set([file_menu_image_src,file_menu_image_results],'callback',{@change_directory,APP});
set(file_menu_mod,'callback',{@add_mods, APP});
% set([display_menu_01,display_menu_02,display_menu_03],'callback',{@menu_display_3d_select,APP});
set([display_menu_01,display_menu_03],'callback',{@menu_display_3d_select,APP});
set([image_menu_mask, image_menu_csv],'callback',{@cell_mask_handler, APP});
% set(settings_menu_search,'callback',{@simple_settings_input,APP});
set(settings_menu_search,'callback',{@settings_gui_call,APP});
set(parallel_menu_01,'callback',{@set_par_processes, APP});
set([APP.film_slider,APP.z_slice_slider],'callback',{@display_call,APP});
set([APP.brightness_slider,APP.contrast_slider,APP.cell_boundary_toggle,APP.excluded_signal_toggle],'callback',{@display_call,APP});
set([APP.frame_signal_toggle,APP.cell_signal_toggle,APP.created_cell_selection,APP.remove_signals_button],'callback',{@display_listener,APP});
set([APP.sig_traj_rb1,APP.sig_traj_rb2],'callback',{@display_listener,APP});
% set([APP.curr_keyframe_details_pan,APP.all_keyframe_details_pan,APP.keyframe_map],'buttondownfcn',{@view_keyframes,APP});
% set([APP.curr_keyframe_details,APP.all_keyframe_details],'buttondownfcn',{@view_keyframes,APP});
% set(APP.keyframe_selection,'callback',{@view_keyframes,APP});
% set([APP.add_keyframe_button,APP.create_keyframe_button,APP.modify_keyframe_button,APP.current_threshold_display,APP.current_threshold_slider,APP.start_frame_input,APP.end_frame_input],'callback',{@keyframe_handler,APP});
% set([APP.add_keyframe_button,APP.create_keyframe_button,APP.modify_keyframe_button,APP.current_threshold_display,APP.current_threshold_slider],'callback',{@keyframe_handler,APP});
set([APP.current_threshold_display,APP.current_threshold_slider],'callback',{@wavelet_threshold_callback,APP});
% set([APP.add_object_button,APP.delete_object_button,APP.modify_cell_button],'callback',{@polygon_handler,APP});
set([APP.add_object_button],'callback',{@polygon_create, APP});
set([APP.modify_cell_button],'callback',{@polygon_modify, APP});
set([APP.quick_detect_button],'callback',{@quick_detect_call, APP});
set([APP.full_detect_button],'callback',{@full_detect_call, APP});
% set([APP.add_spots_button],'callback',{@init_spot_creation, APP});
set([APP.create_keyframe_button],'callback',{@create_spot_detection_obj, APP});
set([APP.removal_kf_button],'callback',{@update_exclusion_keyframe_data, APP});
%% initial creation final setup
i_o_setup(APP);

%
%%%
%%%%%
%%%
%

function [] = quick_test(hand,evt)
%% quick_testing_tool
% 

disp('evt registered');

