function [INSPECT] = create_inspection_figure(I,spotInfo,pt_clicked)
%% fxn for creation of figure to inspect image and signals
%  assigns necessary callbacks for various components
%  
%  INPUT:
%  .  I - the image [x y z]
%  .  spotInfo - structure containing information for current image signals
%                with the keyframe shown in the previous gui
%  .  pt_clicked - point user was examining previously
%  
%  OUTPUT:
%  .  INSPECT - figure struct containing all graphic components and data
%               for this inspection figure
%  
%

%% creating figure
INSPECT.figure_handle = figure('units','normalized',...
                               'position',[0.25 0.2 0.5 0.6],...
                               'name','Inspector Tool',...
                               'resize','on',...
                               'numbertitle','off');
%
INSPECT.image_axis = axes('units','normalized',...
                          'position',[0.58 0.28 0.4 0.7],...
                          'YDir','reverse',...
                          'XTick',[],...
                          'YTick',[]);
%
INSPECT.signal_axis = axes('units','normalized',...
                           'position',[0.58 0.28 0.4 0.7],...
                           'color','none',...
                           'YDir','reverse',...
                           'XAxisLocation','top',...
                           'NextPlot','add',...
                           'HitTest','on',...
                           'PickableParts','visible',...
                           'XTick',[],...
                           'YTick',[]);
%
% INSPECT.sig_ax_tb = axtoolbar(INSPECT.signal_axis,{'pan','zoomin','zoomout'});
%
INSPECT.hist_ax = axes('units','normalized',...
                       'position',[0.05 0.72 0.5 0.26],...
                       'HitTest','on',...
                       'PickableParts','visible',...
                       'NextPlot','add');
%
slide_max = size(I,3);
slide_step = 1/(slide_max - 1);
if slide_step > 1
    slide_step = 1;
end
INSPECT.z_slice_slider = uicontrol('style','slider',...
                                   'units','normalized',...
                                   'position',[0.5575 0.28 0.015 0.7],...
                                   'min',1,...
                                   'max',slide_max,...
                                   'value',1,...
                                   'sliderstep',[slide_step slide_step],...
                                   'visible','on',...
                                   'enable','off');
%% image adjustment panel
INSPECT.b_c_panel = uipanel('units','normalized',...
                            'Position',[0.58 0.02 0.4 0.24],...
                            'Title','Image Adjustment');
%
INSPECT.b_label = uicontrol('style','text',...
                            'parent',INSPECT.b_c_panel,...
                            'units','normalized',...
                            'position',[0.02 0.745 0.2 0.195],...
                            'string','Brightness');
%
INSPECT.brightness_slider = uicontrol('style','slide',...
                                      'parent',INSPECT.b_c_panel,...
                                      'units','normalized',...
                                      'position',[0.02 0.7 0.26 0.075],...
                                      'min',-1,'max',1,...
                                      'SliderStep',[0.01 0.01],...
                                      'Value',0,...
                                      'Enable','on');
%
INSPECT.c_label = uicontrol('style','text',...
                            'parent',INSPECT.b_c_panel,...
                            'units','normalized',...
                            'position',[0.02 0.295 0.2 0.195],...
                            'string','Contrast');
%
INSPECT.contrast_slider = uicontrol('style','slide',...
                                    'parent',INSPECT.b_c_panel,...
                                    'units','normalized',...
                                    'position',[0.02 0.25 0.26 0.075],...
                                    'min',1,'max',74,...
                                    'Value',49,...
                                    'SliderStep',[0.01 0.075],...
                                    'Enable','on');
%
INSPECT.rb_image_group = uibuttongroup(INSPECT.b_c_panel,'Units','normalized',...
                                                         'Visible','on',...
                                                         'Position',[0.525 0.525 0.45 0.45],...
                                                         'BorderType','none');
INSPECT.rb_image_mip = uicontrol(INSPECT.rb_image_group,'style','radiobutton',...
                                                        'units','normalized',...
                                                        'Position',[0.05 0.05 0.9 0.45],...
                                                        'String','Display Max Z-Project',...
                                                        'Value',1,...
                                                        'Tag','MIP');
INSPECT.rb_image_slice = uicontrol(INSPECT.rb_image_group,'style','radiobutton',...
                                                          'units','normalized',...
                                                          'Position',[0.05 0.55 0.9 0.45],...
                                                          'String','Display Z-Slice',...
                                                          'Tag','SLICE');
%
INSPECT.apply_settings_button = uicontrol('style','pushbutton',...
                                          'parent',INSPECT.b_c_panel,...
                                          'units','normalized',...
                                          'position',[0.55 0.05 0.4 0.4],...
                                          'value',0,...
                                          'String','Apply Settings to Keyframe',...
                                          'Enable','on',...
                                          'Tag','push_me');
%
%% pixel values axis setup
INSPECT.pixels_axis = axes('units','normalized',...
                           'position',[0.05 0.28 0.32 0.36],...
                           'YDir','reverse',...
                           'NextPlot','add',...
                           'XTick',[],...
                           'YTick',[]);
%
INSPECT.invisible_axis = axes('units','normalized',...
                              'position',[0.05 0.28 0.32 0.36],...
                              'YDir','reverse',...
                              'color','none',...
                              'NextPlot','add',...
                              'XTick',[],...
                              'YTick',[]);
%
linkaxes([INSPECT.pixels_axis,INSPECT.invisible_axis]);
%
INSPECT.z_profile = axes('units','normalized',...
                         'Position',[0.38 0.28 0.17 0.36],...
                         'visible','on',...
                         'PickableParts','none',...
                         'HitTest','off',...
                         'NextPlot','add');
% xlabel(INSPECT.z_profile,'Pixel Intensity');
% ylabel(INSPECT.z_profile,'Slice No.');
%
INSPECT.small_display_box = uicontrol('style','text',...
                                      'units','normalized',...
                                      'position',[0.05 0.28 0.32 0.02],...
                                      'visible','on',...
                                      'String','HERE');
%% another panel
INSPECT.data_panel = uipanel('units','normalized',...
                             'Position',[0.05 0.02 0.5 0.24],...
                             'Title','Signal Processing');
INSPECT.offset_label = uicontrol('style','text',...
                                 'parent',INSPECT.data_panel,...
                                 'units','normalized',...
                                 'position',[0.02 0.745 0.2 0.195],...
                                 'string','Pixel Offset');
INSPECT.offset_slider = uicontrol('style','slider',...
                                  'parent',INSPECT.data_panel,...
                                  'units','normalized',...
                                  'position',[0.02 0.7 0.26 0.075],...
                                  'min',0,'max',10,...
                                  'SliderStep',[0.1 0.1],...
                                  'value',1,...
                                  'enable','on');
INSPECT.background_label = uicontrol('style','text',...
                                     'parent',INSPECT.data_panel,...
                                     'units','normalized',...
                                     'position',[0.02 0.295 0.2 0.195],...
                                     'String','Pixel Background');
INSPECT.background_slider = uicontrol('style','slider',...
                                      'parent',INSPECT.data_panel,...
                                      'units','normalized',...
                                      'position',[0.02 0.25 0.26 0.075],...
                                      'min',1,'max',11,...
                                      'SliderStep',[0.1 0.1],...
                                      'Value',1,...
                                      'enable','on');
%
INSPECT.min_intensity_label = uicontrol('style','text',...
                                        'parent',INSPECT.data_panel,...
                                        'units','normalized',...
                                        'position',[0.3 0.785 0.2 0.195],...
                                        'String','Minimum Signal Intensity');
%
INSPECT.min_intensity_box = uicontrol('style','edit',...
                                      'parent',INSPECT.data_panel,...
                                      'units','normalized',...
                                      'position',[0.5 0.785 0.14 0.195],...
                                      'enable','on');
%
INSPECT.max_intensity_label = uicontrol('style','text',...
                                        'parent',INSPECT.data_panel,...
                                        'units','normalized',...
                                        'position',[0.3 0.435 0.2 0.195],... % [0.65 0.785 0.2 0.195]
                                        'String','Maximum Signal Intensity');
%
INSPECT.max_intensity_box = uicontrol('style','edit',...
                                      'parent',INSPECT.data_panel,...
                                      'units','normalized',...
                                      'position',[0.5 0.435 0.14 0.195],... % [0.85 0.785 0.14 0.195]
                                      'enable','on');
%
INSPECT.min_size_label = uicontrol('style','text',...
                                   'parent',INSPECT.data_panel,...
                                   'units','normalized',...
                                   'position',[0.65 0.785 0.2 0.195],... % [0.3 0.435 0.2 0.185]
                                   'String','Minimum Signal Size',...
                                   'enable','off');
%
INSPECT.min_size_box = uicontrol('style','edit',...
                                 'parent',INSPECT.data_panel,...
                                 'units','normalized',...
                                 'position',[0.85 0.785 0.14 0.195],... % [0.5 0.435 0.14 0.195]
                                 'enable','off');
%
INSPECT.max_size_label = uicontrol('style','text',...
                                   'parent',INSPECT.data_panel,...
                                   'units','normalized',...
                                   'position',[0.65 0.435 0.2 0.195],...
                                   'String','Maximum Signal Size',...
                                   'enable','off');
%
INSPECT.max_size_box = uicontrol('style','edit',...
                                 'parent',INSPECT.data_panel,...
                                 'units','normalized',...
                                 'position',[0.85 0.435 0.14 0.195],...
                                 'enable','off');
%
INSPECT.int_histogram_button = uicontrol('style','push',...
                                         'parent',INSPECT.data_panel,...
                                         'units','normalized',...
                                         'position',[0.39 0.08 0.25 0.27],...
                                         'String','Intensity Histogram',...
                                         'enable','on');
%
INSPECT.size_histogram_button = uicontrol('style','push',...
                                          'parent',INSPECT.data_panel,...
                                          'units','normalized',...
                                          'position',[0.74 0.08 0.25 0.27],...
                                          'String','Size Histogram',...
                                          'enable','on');
%
%% additional setup
setappdata(INSPECT.figure_handle,'image',I);
setappdata(INSPECT.figure_handle,'spotInfo',spotInfo);

co = [0 0.4470 0.7410; 0.8500 0.3250 0.0980; 0.9290 0.6940 0.1250; 0.4940,...
    0.1840 0.5560; 0.4660 0.6740 0.1880; 0.3010 0.7450 0.9330; 0.6350 0.0780 0.1840];
setappdata(INSPECT.figure_handle,'color_matrix',co);

inspector_display_setup(INSPECT,I);
inspector_histogram_setup(INSPECT,I,spotInfo);

%% callback assignment
set([INSPECT.signal_axis],'ButtonDownFcn',{@inspector_image_clicked,INSPECT});
set([INSPECT.brightness_slider,INSPECT.contrast_slider],'Callback',{@inspector_display_image,INSPECT});
set([INSPECT.offset_slider,INSPECT.background_slider],'Callback',{@inspector_bg_update,INSPECT});
set([INSPECT.int_histogram_button,INSPECT.size_histogram_button],'Callback',{@swap_intensity_and_size,INSPECT});
set(INSPECT.rb_image_group,'SelectionChangedFcn',{@inspector_display_image,INSPECT});
set(INSPECT.apply_settings_button,'Callback',{@return_to_app_handler,INSPECT});

%
% final setup step w/ input pt
scatter(INSPECT.signal_axis,pt_clicked(1,1),pt_clicked(1,2),75,'yellow',...
        'LineWidth',1.25,'tag','user_tagged');
tmp_struct = struct;
tmp_struct.IntersectionPoint = pt_clicked;
inspector_image_clicked(INSPECT.signal_axis,tmp_struct,INSPECT);
%

%
%%%
%%%%%
%%%
%