function [INSPECT] = tmp_inspect_fig(I, spotInfo, pt_clicked)
%% <placeholder>
%

%
INSPECT.figure_handle = figure('units','normalized',...
                               'position',[0.15 0.15 0.75 0.6],...
                               'name','Inspector Tool',...
                               'resize','on',...
                               'numbertitle','off',...
                               'menubar','none',...
                               'toolbar','none');
%
INSPECT.image_axis = axes('units','normalized',...
                          'position',[0.58 0.15 0.41 0.8],...
                          'YDir','reverse',...
                          'XTick',[],...
                          'YTick',[]);
%
INSPECT.signal_axis = axes('units','normalized',...
                           'position',[0.58 0.15 0.41 0.8],...
                           'color','none',...
                           'YDir','reverse',...
                           'XAxisLocation','top',...
                           'NextPlot','add',...
                           'HitTest','on',...
                           'PickableParts','visible',...
                           'XTick',[],...
                           'YTick',[]);
%
INSPECT.pixels_axis = axes('units','normalized',...
                           'position',[0.01 0.45 0.32 0.5],...
                           'YDir','reverse',...
                           'NextPlot','add',...
                           'XTick',[],...
                           'YTick',[]);
%
INSPECT.invisible_axis = axes('units','normalized',...
                              'position',[0.01 0.45 0.32 0.5],...
                              'YDir','reverse',...
                              'color','none',...
                              'NextPlot','add',...
                              'XTick',[],...
                              'YTick',[]);
%
linkaxes([INSPECT.pixels_axis,INSPECT.invisible_axis]);
%
slide_max = size(I,3);
slide_step = 1/(slide_max - 1);
if slide_step > 1
    slide_step = 1;
end
INSPECT.z_slice_slider = uicontrol('style','slider',...
                                   'units','normalized',...
                                   'position',[0.5575 0.15 0.015 0.8],...
                                   'min',1,...
                                   'max',slide_max,...
                                   'value',1,...
                                   'sliderstep',[slide_step slide_step],...
                                   'visible','on',...
                                   'enable','off');
%
INSPECT.z_profile = axes('units','normalized',...
                         'Position',[0.38 0.45 0.165 0.5],...
                         'visible','on',...
                         'PickableParts','none',...
                         'HitTest','off',...
                         'NextPlot','add');
%
INSPECT.small_display_box = uicontrol('style','text',...
                                      'units','normalized',...
                                      'position',[0.01 0.45 0.325 0.02],...
                                      'visible','on',...
                                      'String','HERE');
%[0.01 0.15 0.325 0.2]
INSPECT.data_panel = uipanel('units','normalized',...
                             'Position',[0.22 0.15 0.325 0.2],...
                             'Title','Background Correction');
INSPECT.offset_label = uicontrol('style','text',...
                                 'parent',INSPECT.data_panel,...
                                 'units','normalized',...
                                 'position',[0.02 0.78 0.5 0.2],...
                                 'string','Pixel Offset');
INSPECT.offset_slider = uicontrol('style','slider',...
                                  'parent',INSPECT.data_panel,...
                                  'units','normalized',...
                                  'position',[0.02 0.6 0.45 0.125],...
                                  'min',0,'max',10,...
                                  'SliderStep',[0.1 0.1],...
                                  'value',1,...
                                  'enable','on');
INSPECT.background_label = uicontrol('style','text',...
                                     'parent',INSPECT.data_panel,...
                                     'units','normalized',...
                                     'position',[0.02 0.33 0.5 0.2],...
                                     'String','Pixel Background');
INSPECT.background_slider = uicontrol('style','slider',...
                                      'parent',INSPECT.data_panel,...
                                      'units','normalized',...
                                      'position',[0.02 0.15 0.45 0.125],...
                                      'min',1,'max',11,...
                                      'SliderStep',[0.1 0.1],...
                                      'Value',1,...
                                      'enable','on');
%
INSPECT.create_keyframe_button = uicontrol('style','push',...
                                           'parent',INSPECT.data_panel,...
                                           'units','normalized',...
                                           'position',[0.525 0.05 0.45 0.45],...
                                           'value',0,...
                                           'string','Create BKGD / OFF Keyframe');
%
INSPECT.cancel_keyframe_button = uicontrol('style','push',...
                                           'parent',INSPECT.data_panel,...
                                           'units','normalized',...
                                           'position',[0.525 0.55 0.45 0.45],...
                                           'value',0,...
                                           'string','Close Inspector');
%[0.345 0.15 0.2 0.2]
INSPECT.b_c_panel = uipanel('units','normalized',...
                            'Position',[0.01 0.15 0.2 0.2],...
                            'Title','Image Adjustment');
%
INSPECT.b_label = uicontrol('style','text',...
                            'parent',INSPECT.b_c_panel,...
                            'units','normalized',...
                            'position',[0.02 0.78 0.4 0.2],...
                            'string','Brightness');
%
INSPECT.brightness_slider = uicontrol('style','slide',...
                                      'parent',INSPECT.b_c_panel,...
                                      'units','normalized',...
                                      'position',[0.02 0.65 0.4 0.125],...
                                      'min',-1,'max',1,...
                                      'SliderStep',[0.01 0.01],...
                                      'Value',0,...
                                      'Enable','on');
%
INSPECT.c_label = uicontrol('style','text',...
                            'parent',INSPECT.b_c_panel,...
                            'units','normalized',...
                            'position',[0.02 0.45 0.4 0.2],...
                            'string','Contrast');
%
INSPECT.contrast_slider = uicontrol('style','slide',...
                                    'parent',INSPECT.b_c_panel,...
                                    'units','normalized',...
                                    'position',[0.02 0.325 0.4 0.125],...
                                    'min',1,'max',74,...
                                    'Value',49,...
                                    'SliderStep',[0.01 0.075],...
                                    'Enable','on');
%
INSPECT.rb_image_group = uibuttongroup(INSPECT.b_c_panel,'Units','normalized',...
                                                         'Visible','on',...
                                                         'Position',[0.475 0.325 0.5 0.625],...
                                                         'BorderType','none');
%
INSPECT.rb_image_mip = uicontrol(INSPECT.rb_image_group,'style','radiobutton',...
                                                        'units','normalized',...
                                                        'Position',[0.025 0.025 0.9 0.475],...
                                                        'String','Max Z-Project',...
                                                        'Value',1,...
                                                        'Tag','MIP');
%
INSPECT.rb_image_slice = uicontrol(INSPECT.rb_image_group,'style','radiobutton',...
                                                          'units','normalized',...
                                                          'Position',[0.025 0.525 0.9 0.475],...
                                                          'String','Full 3D Stack',...
                                                          'Tag','SLICE');
%
%% toolbar essentials
%  zoom in / zoom out / pan / 
set(INSPECT.figure_handle,'toolbar','figure');
tmp_cell_array = {'Show Plot Tools and Dock Figure','Hide Plot Tools',...
                    'Print Figure','Save Figure','Open File',...
                    'New Figure','Insert Legend','Insert Colorbar',...
                    'Data Cursor','Rotate 3D','Link Plot','Edit Plot',...
                    'Brush/Select Data'};
tooltip_string_array = string(tmp_cell_array);
a = findall(gcf);
for i=1:size(tooltip_string_array,2)
    tmp_string = char(tooltip_string_array(1,i));
    b = findall(a,'ToolTipString',tmp_string);
    set(b,'Visible','off');
end

%% initial object assignment
%  image / spotInfo /
setappdata(INSPECT.figure_handle,'image',I);
setappdata(INSPECT.figure_handle,'spotInfo',spotInfo);

%% global color matrix
%
co = [0 0.4470 0.7410; 0.8500 0.3250 0.0980; 0.9290 0.6940 0.1250; 0.4940,...
    0.1840 0.5560; 0.4660 0.6740 0.1880; 0.3010 0.7450 0.9330; 0.6350 0.0780 0.1840];
setappdata(INSPECT.figure_handle,'color_matrix',co);

%% callback assignment
%

set([INSPECT.signal_axis],'ButtonDownFcn',{@inspector_image_clicked, INSPECT});
set([INSPECT.brightness_slider,INSPECT.contrast_slider],'callback',{@inspector_display_image, INSPECT});
set([INSPECT.offset_slider,INSPECT.background_slider],'callback',{@inspector_bg_update, INSPECT});
set(INSPECT.rb_image_group,'SelectionChangedFcn',{@inspector_display_image,INSPECT});
set([INSPECT.cancel_keyframe_button,INSPECT.create_keyframe_button],'callback',{@return_to_app,INSPECT});

%% inspector setup calls
%
inspector_display_setup(INSPECT,I);
if ~isempty(pt_clicked)
    scatter(INSPECT.signal_axis,pt_clicked(1,1),pt_clicked(1,2),100,'yellow',...
        'linewidth',1.25,'tag','user_tagged');
    tmp_struct = struct;
    tmp_struct.IntersectionPoint = pt_clicked;
    inspector_image_clicked(INSPECT.signal_axis,tmp_struct,INSPECT);
end
axis_display_sync(INSPECT, INSPECT.pixels_axis, INSPECT.invisible_axis);


%
%%%
%%%%%
%%%
%